#!/usr/bin/env bash
export PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin

TARGET=$1
DEPLOY_TREE=$2
VENV=$3

set -e

cd "${DEPLOY_TREE}"
git fetch --all
git checkout --force "${TARGET}"


# Deploy

if [ -f "bower.json" ]
then 
	bower install -f bower.json
fi

source "${VENV}/bin/activate"

pip install -r requirements.txt

./manage.py compilemessages
./manage.py collectstatic --noinput
./manage.py migrate && touch uwsgi.ini
